# Generated by Django 5.1.2 on 2024-10-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_book_genre_customer_address_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Book',
            new_name='book',
        ),
    ]
