# Generated by Django 5.1.2 on 2024-10-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_book_orderitem_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
