# Generated by Django 5.1.2 on 2024-10-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
